### ISSUE TITLE
Integration with starlight

### ISSUE THREAD

**Issue by Asmatzaile** [shishkin/astro-asciidoc#27]
I'm trying to set up an astro starlight project with astro-asciidoc but I'm having trouble with it. Is it possible?

**Comment by shishkin** [comment]
I didn't try it but it should work in any astro application. What exactly did you try and what errors you see?

**Comment by Asmatzaile** [comment]
I installed astro with starlight and then astro-asciidoc and added it to integrations. Starlight [expects](https://starlight.astro.build/guides/project-structure/#files-and-directories) files to be inside `src/content/docs`; when i put .adoc files there, they seem to be ignored.
I think it has to do with [content collections](https://docs.astro.build/en/guides/content-collections/) and the way they are handled, but no idea.
I also tried to install first astro-asciidocs, check that it did work, and then manually install starlight; where it stopped working (.adoc files being ignored).

**Comment by shishkin** [comment]
@Asmatzaile I've just checked and astro-asiidoc integration works in a new starlight project with `.adoc` pages inside `src/pages/` directory. Astro content collections unfortunately are tied to markdown and MDX and won't allow custom file types and loaders (at least I haven't found any relevant APIs). You can however always have your own `[...slug].astro` page and render Asciidoc like in the [load example](https://github.com/shishkin/astro-asciidoc/blob/main/example/src/pages/load.

So, unless Astro content collections provide custom file type support, I think, astro-asciidoc won't work with starlight out of the box.
