### ISSUE TITLE
support autogenerate in pages

### ISSUE THREAD

**Issue by Soltus** [shishkin/astro-asciidoc#29]

**Comment by shishkin** [comment]
Can you provide more details of you use case?

**Comment by Soltus** [comment]
I think I made a mistake. I used starlight to automatically generate the sidebar, but it doesn't support adoc format so I don't see it in the build. Does this mean I can only ask starlight for help?

**Comment by shishkin** [comment]
Yes, Starlight relies on Astro Content Collections and they only support Markdown. I'll close this issue for now.
