### ISSUE TITLE
How to configure the extensions

### ISSUE THREAD

**Issue by beyondlex** [shishkin/astro-asciidoc#31]
Hi! Thanks for this awesome plugin! I want to know if it is possible to integrate the Asciidoctor diagram extension [asciidoctor-kroki](https://github.com/asciidoctor/asciidoctor-kroki) as an extension of astro-asciidoc?

```js
export default defineConfig({
  integrations: [
    asciidoc({
      options: {},
      extensions: [ 'asciidoctor-kroki' ], // Is this possible ? 
    },
  ]
})
```

**Comment by shishkin** [comment]
Thanks. Yes, it should be possible. Did you try it and had any issued with that? As long as asciidoctor options are serializable as JSON (e.g. not contain JS functions), they will be passed to asciidoctor "as is". Let me know if it doesn't work.

**Comment by shishkin** [comment]
Closing as inactive
